### ISSUE TITLE
Transition between inactive and speaking shows background

### ISSUE THREAD

**Issue by Ligerx** [Fugiman/discord-reactive-images#47]
Hi, thanks for hosting this service!

I noticed that when transitioning between the two states, the images are both transparent for a small period of time. This means that whatever's behind the images will be seen. It's a subtle issue.

**Comment by Ligerx** [comment]
haven't tested it myself, but if you remove the opacity on this line, I think this solves the issue without any side effects right?

https://github.com/Fugiman/discord-reactive-images/blob/57e6fac6bb48050964912d2f428b832f8712e221/pages/group.vue#L101

**Comment by Fugiman** [comment]
The opacity styling is required as there is no guarantee that the speaking & inactive PNGs are the same size/shape. Some people may put an outline on the speaking image, or have a different pose entirely. The current code does a 200ms cross-fade between the two, so yes at a certain point both images are at 50% opacity and you can see what's behind them.

There is a warning on the manage page to not use Reactive Images to obscure content, and it applies here as well. If there's something you need hidden please explicitly obscure it some other way. I don't intend to adjust Reactive Images to accommodate this use case.

Otherwise if it's purely an aesthetic thing I'd appreciate a gif or video of this in action to help show what looks bad about it.

**Comment by Ligerx** [comment]
It's not a big deal, just something I noticed as I was testing this out. It makes sense why it's set up this way given images might be very different. My png is basically the same except with the mouth open.

**Comment by Fugiman** [comment]
I've adjusted the crossfading to have less background leaking through, hope it helps! https://twitter.com/Fugiman/status/1390092603417190401

**Comment by Ligerx** [comment]
Yes, there's noticeably less ghosting of the stuff behind me in my stream overlays. Thanks for the quick fix 😀
